seed:
  default: 789
  model_init: 789
  batch_order: 789
data:
  gpu: 1
  num_workers: 4
  train_dataset: ./dataset_ffcv/cifar_train.beton
  eval_dataset: ./dataset_ffcv/cifar_test.beton
training:
  batch_size: 512
  epochs: 24
  lr: 0.5
  momentum: 0.9
  lr_peak_epoch: 5
  weight_decay: 5e-4
  label_smoothing: 0.1
  num_workers: 4
eval:
  lr_tta: false
logging:
  log_level: 2
exp:
  folder: ./Experiments/CIFAR100_Baseline/
  ablation: temp
  ix: 0
model:
  model_name: resnet9